branch-defaults:
  "AWS\u30C7\u30D7\u30ED\u30A4":
    environment: stock-info-dev
    group_suffix: null
environment-defaults:
  stock-info-dev:
    branch: null
    repository: null
global:
  application_name: stock-info
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Puma with Ruby 2.6 running on 64bit Amazon Linux
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
